mytest/firstapp/urls.py
from django.urls import path

from .views import (
  FirstAppCreateView,
  FirstAppListView,
  FirstAppUpdateView,
  FirstAppDeleteView,
  FirstAppDetailView
  )


app_name = 'firstapp'

urlpatterns = [
    path('create/', FirstAppCreateView.as_view(), name='create'),
    path('list/', FirstAppListView.as_view(), name='list'),
    path('edit/<int:pk>', FirstAppUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', FirstAppDeleteView.as_view(), name='delete'),
    path('details/<int:pk>', FirstAppDetailView.as_view(), name='details'),
]

mytest/mytest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firstapp.urls', namespace='firstapp')),
    path('', include('users.urls', namespace='users')),
]

mytest/users/urls.py
from django.urls import path

from django.contrib.auth import views
from django.urls import reverse_lazy

from .views import register, activate


app_name = 'users'

urlpatterns = [
  path('login/', views.LoginView.as_view(template_name='users/login.html'), name='login'),
  path('logout/', views.LogoutView.as_view(template_name='users/logged_out.html'), name='logout'),

  path('password-change/', views.PasswordChangeView.as_view(success_url=reverse_lazy('users:password_change_done'), template_name='users/password_change.html'), name='password_change'),
  path('password-change/done/', views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),

  path('password-reset/', views.PasswordResetView.as_view(email_template_name='users/password_reset_email.html', success_url=reverse_lazy('users:password_reset_done'),
    template_name='users/password_reset_form.html'), name='password_reset'),
  path('password-reset/done/', views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
  path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('users:password_reset_complete'), template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
  path('reset/done/', views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),

  path('register/', register, name='register'),
  path('register/activation/', views.TemplateView.as_view(template_name='users/account_activation_sent.html'), name='account_activation_sent'),
  path('register/activate/<uidb64>/<token>/', activate, name='activate'),
  path('register/done/', views.TemplateView.as_view(template_name='users/register_done.html'), name='register_done'),
]

mytest/users/models.py
from django.db import models

# Create your models here.

mytest/users/forms.py
from django import forms # Проверить необходимость.

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

"""
class UserRegistrationForm(forms.ModelForm):
    # Форма регистрации пользователя

    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        #fields = '__all__'
        fields = ('username', 'first_name', 'email') # Везде поменять на кортежи.

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']
"""

class UserRegistrationForm(UserCreationForm):
    # Форма регистрации пользователя

    email = forms.EmailField(max_length=254, help_text='Это поле обязательно')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', ) # Везде поменять на кортежи.

mytest/users/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import redirect
#from django.contrib.auth import login, authenticate
from django.urls import reverse_lazy
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.contrib.auth.models import User
from django.contrib import messages

from .forms import UserRegistrationForm
from mytest.tokens import account_activation_token


def register(request):   
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            current_site = get_current_site(request)
            subject = 'Активируйте свой аккаунт'
            message = render_to_string('users/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)
            messages.success(request, 'Вы успешно зарегистрированы')

            return redirect(reverse_lazy('users:account_activation_sent'))
        else:
            messages.error(request, 'Проверьте корректность заполненных полей')
    else:
        form = UserRegistrationForm()
        
    return render(request, 'users/register.html', {'form': form})

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        #login(request, user)
        return redirect(reverse_lazy('users:register_done'))
    else:
        return render(request, 'users/account_activation_invalid.html')

mytest/templates/users/account_activation_email.html
{% load i18n %}{% autoescape off %}

Здравствуйте, {{ user.username }}.

Пожалуйста, перейдите по ссылке ниже для завершения регистрации:
http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

mytest/templates/users/account_activation_invalid.html
{% extends 'main.html' %}

{% block title %}Активация аккаунта{% endblock %}

{% block main_data %}
<div class="card" align="center">
    <div class="card-body">
        <h2 class="card-title">Активация аккаунта</h2>
        <br>
        <p>При подтверждении электронной почты произошла ошибка. Возможно, ссылка уже была использована.</p>
        <a href="{% url 'users:login' %}">Вернуться на страницу входа</a>
    </div>
</div>
{% endblock %}

mytest/templates/users/account_activation_sent.html
{% extends 'main.html' %}

{% block title %}Активация аккаунта{% endblock %}

{% block main_data %}
<div class="card" align="center">
    <div class="card-body">
        <h2 class="card-title">Активация аккаунта</h2>
        <br>
        <p>На Ваш электронный адрес было выслано письмо с ссылкой для подтверждения.</p>
        <a href="{% url 'users:login' %}">Вернуться на страницу входа</a>
    </div>
</div>
{% endblock %}

mytest/templates/users/logged_out.html
{% extends 'main.html' %}

{% block title %}Выход{% endblock %}

{% block main_data %}
<div class="container" align="center">
    <br>
    <!--
    {% if user.is_authenticated %}
        <p>Вы вышли из аккаунта.</p>
        <a href="{% url 'users:login' %}">Войти еще раз</a>
    {% else %}
        <p>Необходимо сначала <a href="{% url 'users:login' %}">войти</a>.</p>
    {% endif %}
    -->
    <p>Вы вышли из аккаунта.</p>
    <a href="{% url 'users:login' %}">Войти еще раз</a>
</div>
{% endblock %}

mytest/templates/users/login.html
{% extends 'main.html' %}

{% block title %}Вход{% endblock %}

{% block main_data %}
<div class="card" align="center">
    <div class="card-body">
        {% if user.is_authenticated %}
            <p>Вы уже вошли как <b>{{ user.username }}</b>.</p>
        {% else %}
        <h2 class="card-title">Войти в аккаунт</h2>
        <br>
        <p>Если у Вас нет аккаунта, Вы можете <a href="{% url 'users:register' %}">зарегистрироваться</a></p>
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">
            
            <!--{{ form.as_p }}-->
            {{ form }}
            
            <button type="submit" class="btn btn-primary btn-block">Войти</button>
            <a href="{% url 'users:password_reset' %}">Забыли пароль?</a>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

mytest/templates/users/password_change.html
{% extends 'main.html' %}

{% block title %}Смена пароля{% endblock %}

{% block main_data %}
<div class="card" align="center">
    <div class="card-body">
        <h2 class="card-title">Смена пароля</h2>
        <br>
        <form method="post">

            {% csrf_token %}
            <!--{{ form.as_p }}-->
            {{ form }}
        
            <button type="submit" class="btn btn-success">Сменить пароль</button>
        </form>
    </div>
</div>
{% endblock %}

mytest/templates/users/password_change_done.html
{% extends 'main.html' %}

{% block title %}Смена пароля{% endblock %}

{% block main_data %}
<div class="container" align="center">
    <br>
    <p>Ваш пароль успешно изменен.</p>
    <a href="{% url 'firstapp:list' %}">Мои записки</a>
</div>
{% endblock %}

mytest/templates/users/password_reset_complete.html
{% extends 'main.html' %}

{% block title %}Смена пароля{% endblock %}

{% block main_data %}
<div class="container" align="center">
    <br>
    <p>Ваш пароль успешно изменен.</p>
    <a href="{% url 'users:login' %}">Войти с помощью нового пароля</a>
</div>
{% endblock %}

mytest/templates/users/password_reset_confirm.html
{% extends 'main.html' %}

{% block title %}Смена пароля{% endblock %}

{% block main_data %}
<!--
<div class="container" align="center">
    <br>
    <p>Подтвердите сброс пароля по электронной почте.</p>
    <a href="{% url 'users:login' %}">Вернуться на страницу входа</a>
</div>
-->
<div class="card" align="center">
    <div class="card-body">
        <h2 class="card-title">Смена пароля</h2>
        <br>
        <form method="post">
            {% csrf_token %}
            <!--{{ form.as_p }}-->
            {{ form }}
        
            <button type="submit" class="btn btn-primary btn-block">Сменить</button>
        </form>
    </div>
</div>
{% endblock %}

mytest/templates/users/password_reset_done.html
{% extends 'main.html' %}

{% block title %}Сброс пароля{% endblock %}

{% block main_data %}
<!--
<div class="container" align="center">
    <br>
    <p>Ваш пароль успешно сброшен.</p>
    <a href="{% url 'users:login' %}">Войти с помощью нового пароля</a>
</div>
-->
<div class="container" align="center">
    <br>
    <p>На Ваш электронный адрес выслано письмо с ссылкой для подтверждения сброса пароля.</p>
    <a href="{% url 'users:login' %}">Вернуться на страницу входа</a>
</div>
{% endblock %}

mytest/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

mytest/templates/users/password_reset_form.html
{% extends 'main.html' %}

{% block title %}Сброс пароля{% endblock %}

{% block main_data %}
<div class="card" align="center">
    <div class="card-body">
        <h2 class="card-title">Сброс пароля</h2>
        <br>
        <form method="post">
            {% csrf_token %}
            <!--<input type="hidden" name="next" value="{{ next }}">-->

            <!--{{ form.as_p }}-->
            {{ form }}
        
            <button type="submit" class="btn btn-primary btn-block">Сбросить</button>
        </form>
    </div>
</div>
{% endblock %}

mytest/templates/users/register.html
{% extends 'main.html' %}

{% block title %}Регистрация{% endblock %}

{% block main_data %}
<div class="card" align="center">
    <div class="card-body">
        {% if user.is_authenticated %}
            <p>Вы уже зарегистрированы как <b>{{ user.username }}</b>.</p>
        {% else %}
            <h2 class="card-title">Создать аккаунт</h2>
            <br>
            <a>Заполните форму ниже:</a>
            <br>
            <br>
            <form action="." method="post">
                {% csrf_token %}
                
                <!--{{ form.as_p }}-->
                {{ form }}

                <!--
                {% for field in form %}
                <p>
                    {{ field.label_tag }}<br>
                    {{ field }}
                    {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </p>
                {% endfor %}
                -->
                
                <br>
                <br>
                <button type="submit" class="btn btn-primary btn-block">Зарегистрироваться</button>
                <br>
                <a href="{% url 'users:login' %}">Вернуться на страницу входа</a>
            </form>
        {% endif %}
    </div>
</div>
{% endblock %}

mytest/templates/users/register_done.html
{% extends 'main.html' %}

{% block title %}Добро пожаловать{% endblock %}

{% block main_data %}
<div class="card" align="center">
    <div class="card-body">
        <h2 class="card-title">Добро пожаловать!</h2>
        <!--<h2 class="card-title">Добро пожаловать, {{ user.username }}!</h2>-->
        <br>
        <p>Регистрация успешно завершена. Теперь Вы можете <a href="{% url 'users:login' %}">войти</a>.</p>
    </div>
</div>
{% endblock %}