mytest/firstapp/urls.py
from django.urls import path

from .views import (
  FirstAppCreateView,
  FirstAppListView,
  FirstAppUpdateView,
  FirstAppDeleteView,
  FirstAppDetailView
  )


app_name = 'firstapp'

urlpatterns = [
    path('create/', FirstAppCreateView.as_view(), name='create'),
    path('list/', FirstAppListView.as_view(), name='list'),
    path('edit/<int:pk>', FirstAppUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', FirstAppDeleteView.as_view(), name='delete'),
    path('details/<int:pk>', FirstAppDetailView.as_view(), name='details'),
]

mytest/mytest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firstapp.urls', namespace='firstapp')),
    path('', include('users.urls', namespace='users')),
]

mytest/users/urls.py
from django.urls import path

from django.contrib.auth import views
from django.urls import reverse_lazy

from .views import register, activate


app_name = 'users'

urlpatterns = [
  path('login/', views.LoginView.as_view(template_name='users/login.html'), name='login'),
  path('logout/', views.LogoutView.as_view(template_name='users/logged_out.html'), name='logout'),

  path('password-change/', views.PasswordChangeView.as_view(success_url=reverse_lazy('users:password_change_done'), template_name='users/password_change.html'), name='password_change'),
  path('password-change/done/', views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),

  path('password-reset/', views.PasswordResetView.as_view(email_template_name='users/password_reset_email.html', success_url=reverse_lazy('users:password_reset_done'),
    template_name='users/password_reset_form.html'), name='password_reset'),
  path('password-reset/done/', views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
  path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('users:password_reset_complete'), template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
  path('reset/done/', views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),

  path('register/', register, name='register'),
  path('register/activation/', views.TemplateView.as_view(template_name='users/account_activation_sent.html'), name='account_activation_sent'),
  path('register/activate/<uidb64>/<token>/', activate, name='activate'),
  path('register/done/', views.TemplateView.as_view(template_name='users/register_done.html'), name='register_done'),
]

mytest/firstapp/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import User


class Note(models.Model):
    # Модель записки
    
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    title = models.CharField('Заголовок', max_length=30)
    text = models.CharField('Текст', max_length=250)
    creation_date = models.DateTimeField('Дата создания', auto_now_add=True)
    modify_date = models.DateTimeField('Дата изменения', auto_now=True)

    class Meta:
        ordering = ['creation_date']

    def __str__(self):
        return self.title

mytest/firstapp/forms.py
from django import forms

from .models import Note

class FirstAppForm(forms.ModelForm):
    # Форма создания/изменения записки

    class Meta:
        model = Note
        fields = '__all__'
        #fields = ['title', 'text']

mytest/firstapp/views.py
from django.shortcuts import render

# Create your views here.

from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect

from .models import Note
from .forms import FirstAppForm


class FirstAppCreateView(LoginRequiredMixin, CreateView):
    # Создание записки

    model = Note
    template_name = 'firstapp/operations.html'
    #form_class = FirstAppForm  # get_context_data() got an unexpected keyword argument 'form'
    #fields = '__all__'         # get_context_data() got an unexpected keyword argument 'form'
    fields = ('title', 'text')

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed. It should return an HttpResponse.
        form.instance.author = self.request.user
        if form.is_valid():
            form.save()
        return redirect('firstapp:list')
    
    def get_context_data(self):
        context = super().get_context_data()
        context['action'] = 'Добавить записку'
        return context

class FirstAppListView(LoginRequiredMixin, ListView):
    # Просмотр записок

    model = Note
    template_name = 'firstapp/list.html'
    context_object_name = 'context'
    paginate_by = 15

    def get_queryset(self):
        self.object = Note.objects.filter(author=self.request.user)
        return self.object

class FirstAppDetailView(LoginRequiredMixin, DetailView):
    # Просмотр деталей записки

    model = Note
    template_name = 'firstapp/details.html'
    context_object_name = 'context'
    form_class = FirstAppForm
    #fields = '__all__'

class FirstAppUpdateView(LoginRequiredMixin, UpdateView):
    # Изменение записки

    model = Note
    success_url = reverse_lazy('firstapp:list')
    template_name = 'firstapp/operations.html'
    #form_class = FirstAppForm  # get_context_data() got an unexpected keyword argument 'form'
    #fields = '__all__'         # get_context_data() got an unexpected keyword argument 'form'
    fields = ('title', 'text')

    def get_context_data(self):
        context = super().get_context_data()
        context['action'] = 'Изменить записку'
        return context

class FirstAppDeleteView(LoginRequiredMixin, DeleteView):
    # Удаление записки

    model = Note
    success_url = reverse_lazy('firstapp:list')
    template_name = 'firstapp/delete.html'
    context_object_name = 'context'
    form_class = FirstAppForm
    #fields = '__all__'

mytest/templates/firstapp/delete.html
{% extends 'main.html' %}

{% block title %}Удаление записки{% endblock %}

{% block main_data %}
<div class="container" align="center">
    <br>
	<h2>Удаление записки</h2>
    <br>
    <p>Вы действительно хотите удалить записку "{{ context.title }}"?</p>
    <br>
    <form action="" method="post">
        {% csrf_token %}
        <button class="btn btn-primary" type="submit">Удалить записку</button>
    </form>
</div>
{% endblock %}

mytest/templates/firstapp/details.html
{% extends 'main.html' %}

{% block title %}Детали записки{% endblock %}

{% block main_data %}
<div class="container">
    <br>
	<h2 align="center">Детали записки</h2>
    <br>
    <form>
        <!--
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Записка #:</label>
            <div class="col-sm-10">
                <input class="form-control mb-2" id="id_{{ context.id.name }}" name="id_{{ context.id.name }}" type="text" value="{{ context.id }}" disabled>
            </div>
        </div>
        -->
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Заголовок:</label>
            <div class="col-sm-10">
                <input class="form-control mb-2" id="id_{{ context.title.name }}" name="id_{{ context.title.name }}" type="text" value="{{ context.title }}" disabled>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Дата создания:</label>
            <div class="col-sm-10">
                <input class="form-control mb-2" id="id_{{ context.creation_date.name }}" name="id_{{ context.creation_date.name }}" type="text" value="{{ context.creation_date }}" disabled>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Дата изменения:</label>
            <div class="col-sm-10">
                <input class="form-control mb-2" id="id_{{ context.modify_date.name }}" name="id_{{ context.modify_date.name }}" type="text" value="{{ context.modify_date }}" disabled>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Текст:</label>
            <div class="col-sm-10">
                <textarea class="form-control mb-2" id="id_{{ context.text.name }}" name="{{ context.text.name }}" rows="5" disabled>{{ context.text }}</textarea>
            </div>
        </div>
    </form>
    <br>
</div>
<div align="center">
    <form>
        <button class="btn btn-primary" type="submit" formaction="{% url 'firstapp:list' %}">Назад</button>
        <button class="btn btn-primary" type="submit" formaction="{% url 'firstapp:edit' pk=context.pk %}">Изменить</button>
        <button class="btn btn-primary" type="submit" formaction="{% url 'firstapp:delete' pk=context.pk %}">Удалить</button>
    </form>
</div>
{% endblock %}

mytest/templates/firstapp/list.html
{% extends 'main.html' %}

{% block title %}Мои записки{% endblock %}

{% block main_data %}
<div class="container" align="center">
    <br>
	<h2>Мои записки</h2>
    <br>
    <div>
        <button class="btn btn-primary" onclick="window.location='../create';">Добавить записку</button>
    </div>
    <br>
	{% if context %}
        <table class="table table-hover align-middle">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Заголовок</th>
                    <th scope="col">Текст</th>
                    <th scope="col">Дата создания</th>
                    <th scope="col">Дата изменения</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for row in context %}
                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td>{{row.title|truncatechars:20}}</td>
                        <td>{{row.text|truncatechars:35}}</td>
                        <td>{{row.creation_date}}</td>
                        <td>{{row.modify_date}}</td>
                        <!--
                        <td>
                            <form action="{% url 'firstapp:details' pk=row.pk %}">
                                <button type="submit" class="btn btn-link">Детали</button>
                            </form>
                        </td>
                        <td>
                            <form action="{% url 'firstapp:edit' pk=row.pk %}">
                                <button type="submit" class="btn btn-link">Изменить</button>
                            </form>
                        </td>
                        <td>
                            <form action="{% url 'firstapp:delete' pk=row.pk %}">
                                <button type="submit" class="btn btn-link">Удалить</button>
                            </form>
                        </td>
                        -->
                        <td>
                            <form>
                                <button class="btn btn-default" type="submit" formaction="{% url 'firstapp:details' pk=row.pk %}">
                                    <span class="bi-eye"></span>
                                </button>
                                <button class="btn btn-default" type="submit" formaction="{% url 'firstapp:edit' pk=row.pk %}">
                                    <span class="bi-pen"></span>
                                </button>
                                <button class="btn btn-default" type="submit" formaction="{% url 'firstapp:delete' pk=row.pk %}">
                                    <span class="bi-x"></span>
                                </button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <nav aria-label="Список записок">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">Первая</a></li>
                    <li class="page-item disabled"><a class="page-link" href="#">&laquo;</a></li>
                {% endif %}
                <!--<li class="page-item"><a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>-->
                <li class="page-item"><a class="page-link">{{ page_obj.number }}</a></li>
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">&raquo;</a></li>
                    <li class="page-item disabled"><a class="page-link" href="#">Последняя</a></li>
                {% endif %}
            </ul>
        </nav>
	{% else %}
        <p>У Вас нет записок</p>
	{% endif %}
    <br>
</div>
{% endblock %}

mytest/templates/firstapp/operations.html
{% extends 'main.html' %}

{% block title %}{{ action }}{% endblock %}

{% block main_data %}
<div class="container" style="width: 600px;">
    <br>
    <h2 align="center">{{ action }}</h2>
    <br>
    <form action="" method="post">
        {% csrf_token %}
        <!--{{ form.as_p }}-->
        <div class="mb-3">
            <label class="form-label">{{ form.title.label }}:</label>
            <input class="form-control form-control-lg mb-2" id="id_{{ form.title.name }}" name="{{ form.title.name }}" type="text" placeholder="{{ form.title.label }}"
                required="required" maxlength="{{ form.title.field.max_length }}"{% if form.title.value %}value="{{ form.title.value }}"{% endif %}>

            <label class="form-label">{{ form.text.label }}:</label>
            <textarea class="form-control" id="id_{{ form.text.name }}" name="{{ form.text.name }}" rows="5" placeholder="{{ form.text.label }}"
                required="required" maxlength="{{ form.text.field.max_length }}">{% if form.text.value %}{{ form.text.value }}{% endif %}</textarea>
        </div>
        <div class="submit-row">
            <button class="btn btn-primary" type="submit">{{ action }}</button>
        </div>
    </form>
</div>
{% endblock %}