mytest/firstapp/urls.py
from django.urls import path

from .views import (
  FirstAppCreateView,
  FirstAppListView,
  FirstAppUpdateView,
  FirstAppDeleteView,
  FirstAppDetailView
  )


app_name = 'firstapp'

urlpatterns = [
    path('create/', FirstAppCreateView.as_view(), name='create'),
    path('list/', FirstAppListView.as_view(), name='list'),
    path('edit/<int:pk>', FirstAppUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', FirstAppDeleteView.as_view(), name='delete'),
    path('details/<int:pk>', FirstAppDetailView.as_view(), name='details'),
]

mytest/mytest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firstapp.urls', namespace='firstapp')),
    path('', include('users.urls', namespace='users')),
]

mytest/users/urls.py
from django.urls import path

from django.contrib.auth import views
from django.urls import reverse_lazy

from .views import register, activate


app_name = 'users'

urlpatterns = [
  path('login/', views.LoginView.as_view(template_name='users/login.html'), name='login'),
  path('logout/', views.LogoutView.as_view(template_name='users/logged_out.html'), name='logout'),

  path('password-change/', views.PasswordChangeView.as_view(success_url=reverse_lazy('users:password_change_done'), template_name='users/password_change.html'), name='password_change'),
  path('password-change/done/', views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),

  path('password-reset/', views.PasswordResetView.as_view(email_template_name='users/password_reset_email.html', success_url=reverse_lazy('users:password_reset_done'),
    template_name='users/password_reset_form.html'), name='password_reset'),
  path('password-reset/done/', views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
  path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('users:password_reset_complete'), template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
  path('reset/done/', views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),

  path('register/', register, name='register'),
  path('register/activation/', views.TemplateView.as_view(template_name='users/account_activation_sent.html'), name='account_activation_sent'),
  path('register/activate/<uidb64>/<token>/', activate, name='activate'),
  path('register/done/', views.TemplateView.as_view(template_name='users/register_done.html'), name='register_done'),
]

mytest/templates/main.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Style CSS from static -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <title>{% block title %}Приложение{% endblock %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    {% include 'messages.html' %}

    {% block main_data %}
    {% endblock main_data %}
    <!--
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
  </body>
</html>

mytest/templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div {% if message.tags == 'error' %} class="alert alert-danger alert-dismissible fade show" {% else %} class="alert alert-{{ message.tags }} alert-dismissible fade show" {% endif %} role="alert" align="center">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

mytest/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <a class="navbar-brand" href="{% url 'firstapp:list' %}">Записки</a>
        <div class="collapse navbar-collapse">
            <div class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'firstapp:list' %}">Мои записки</a>
                    <a class="nav-link" href="{% url 'users:password_change' %}">Сменить пароль</a>
                    <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
                {% else %}
                    <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
                    <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
                {% endif %}
            </div>
            <span class="navbar-text">
                Здравствуйте, {% if user.is_authenticated %}{{ user }}{% else %}Гость{% endif %}.
            </span>
        </div>
    </div>
</nav>